version: "3.7"

services:
  poi: 
    container_name: poi
    image: registryezl7212.azurecr.io/poi:2.0
    build: 
      context: ./src/poi/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - services
    volumes:
      - ./secrets:/secrets
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  trips: 
    container_name: trips
    image: registryezl7212.azurecr.io/trips:2.0
    build: 
      context: ./src/trips/
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - services
    volumes:
      - ./secrets:/secrets

  tripviewer: 
    container_name: tripviewer 
    image: registryezl7212.azurecr.io/tripviewer:2.0
    build: 
      context: ./src/tripviewer/
      dockerfile: Dockerfile
    ports:
      - 8082:80
    networks:
      - services
    volumes:
      - ./secrets:/secrets
    environment:
      - USERPROFILE_API_ENDPOINT=http://userprofile
      - TRIPS_API_ENDPOINT=http://trips

  user_java: 
    container_name: user-java
    image: registryezl7212.azurecr.io/user-java:2.0
    build: 
      context: ./src/user-java/
      dockerfile: Dockerfile
    ports:
      - 8083:80
    networks:
      - services
    volumes:
      - ./secrets:/secrets

  userprofile: 
    container_name: userprofile
    image: registryezl7212.azurecr.io/userprofile:2.0 
    build: 
      context: ./src/userprofile/
      dockerfile: Dockerfile
    ports:
      - 8084:80
    networks:
      - services
    volumes:
      - ./secrets:/secrets

  # db:
  #   container_name: db
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   ports:
  #     - 1433:1433
  #   networks:
  #     - services
  #   expose:
  #     - 1433
  #   environment:
  #     - ACCEPT_EULA=Y




networks:
  services:
    driver: 'bridge'



