apiVersion: apps/v1
kind: Deployment
metadata:
  name: tips
  namespace: trip-insights
  labels:
    app: user-java
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - name: user-java
          image: registryezl7212.azurecr.io/user-java:1.0
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 80
              name: user-java