apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: trip-insights
spec:
  selector:
    app: user-java
  type: ClusterIP
  ports:
    - name: user-java
      protocol: TCP
      port: 80
      targetPort: 80