apiVersion: apps/v1
kind: Deployment
metadata:
  name: tips
  namespace: trip-insights
  labels:
    app: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryezl7212.azurecr.io/tripviewer:1.0
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 80
              name: tripviewer