apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: trip-insights
spec:
  selector:
    app: tripviewer
  type: LoadBalancer
  ports:
    - name: tripviewer
      protocol: TCP
      port: 80
      targetPort: 80