apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: trip-insights
  labels:
    app: poi
spec:
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registryezl7212.azurecr.io/poi:1.0
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 80
              name: poi