apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: tripInsights
spec:
  selector:
    app: poi
  type: ClusterIP
  ports:
    - name: poi
      protocol: TCP
      port: 8080
      targetPort: 80