apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryezl7212.azurecr.io/trips:2.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '80'
            - name: CONFIG_FILES_PATH
              value: /etc/k8s/secrets
          resources:
          ports:
            - containerPort: 80
              name: trips
          volumeMounts:
            - name: secrets
              mountPath: "/etc/k8s/secrets"
              readOnly: true
      volumes:
          - name: secrets
            secret:
              secretName: credentials
              optional: false