apiVersion: apps/v1
kind: Deployment
metadata:
  name: tips
  namespace: trip-insights
  labels:
    app: trips
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryezl7212.azurecr.io/trips:1.0
          resources:
          ports:
            - containerPort: 80
              name: trips