apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  selector:
    app: trips
  type: ClusterIP
  ports:
    - name: trips
      protocol: TCP
      port: 80
      targetPort: 80