apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: trip-insights
  labels:
    app: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryezl7212.azurecr.io/userprofile:1.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '80'
            - name: CONFIG_FILES_PATH
              value: /secrets
          resources:
          ports:
            - containerPort: 80
              name: userprofile