apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryezl7212.azurecr.io/userprofile:2.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '80'
            - name: CONFIG_FILES_PATH
              value: /etc/k8s/secrets
          resources:
          ports:
            - containerPort: 80
              name: userprofile
          volumeMounts:
            - name: secrets
              mountPath: "/etc/k8s/secrets"
              readOnly: true
      volumes:
          - name: secrets
            secret:
              secretName: credentials
              optional: false