apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: trip-insights
spec:
  selector:
    app: userprofile
  type: ClusterIP
  ports:
    - name: userprofile
      protocol: TCP
      port: 80
      targetPort: 80